spring:
  application:
    name: api-hacienda
  datasource:
    url: jdbc:mysql://simple-studio-do-user-17834356-0.g.db.ondigitalocean.com:25060/samyx_dev?allowPublicKeyRetrieval=true&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=America/Costa_Rica
    username: doadmin
    password: AVNS_d_4ApkE_ZCXMb-niHbt
  jpa:
    hibernate:
      ddl-auto: none
  jmx:
    default-domain: "API FE Samyx v1.0"
  mail:
    host: smtp.gmail.com
    port: 465
    username: fe@samyx.digital
    password: hgctqnepsmaulkkz
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          starttls:
            enable: false
            required: false
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    debug: true

eureka:
  client:
    service-url:
      defaultZone: https://eureka-server-3nl8a.ondigitalocean.app/eureka/
    register-with-eureka: true
    fetch-registry: true

server:
  port: 8080

correo:
  de:
    distribucion: fe@samyx.digital
  no:
    reply: fe@samyx.digital

path:
  upload:
    files:
      api: XmlClientes/

endpoint:
  prod: https://api.comprobanteselectronicos.go.cr/recepcion/v1/recepcion/
  stag: https://api.comprobanteselectronicos.go.cr/recepcion-sandbox/v1/recepcion/

token:
  prod: https://idp.comprobanteselectronicos.go.cr/auth/realms/rut/protocol/openid-connect/
  stag: https://idp.comprobanteselectronicos.go.cr/auth/realms/rut-stag/protocol/openid-connect/

url:
  qr: ""

cloud:
  aws:
    credentials:
      access-key: DO00KMVVA2PCDAP6B6AV
      secret-key: 6YFkfXRk1+c+V1RU9gClD61O9ccEn+emEGwZHatNa2g
    s3:
      bucket: ssn.soluciones
      endpoint: https://nyc3.digitaloceanspaces.com
      region: nyc3
      prefix: XmlClientes
      url: https://nyc3.digitaloceanspaces.com/ssn.soluciones